services:
  agarden:
    env_file:
      - path: .env
    build: .
    ports:
      - "4321:4321"
    restart: always
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agarden.rule=Host(`trpowell.net`)"
      - "traefik.http.routers.agarden.entrypoints=websecure"
      - "traefik.http.routers.agarden.tls.certResolver=letsencrypt"
      - "traefik.http.services.agarden.loadbalancer.server.port=3000"
networks:
  dokploy-network:
    external: true
